version: '3'
services:
  web-service-qa:
    build: .
    command: gunicorn --timeout 500 --workers 3 -b 0.0.0.0:5001 server:app
    ports:
      - "5001:5001"
    environment:
      FLASK_ENV: production
    networks:
      - shared_network

networks:
  shared_network:
    external: true